{{- $ingress := .Values.keycloak.ingress -}}
{{- $pki := .Values.keycloak.pki -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
    {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
  {{- if $pki.enabled }}
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ include "keycloak.fullname" $ }}-http
              servicePort: https
  {{- else }}
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ include "keycloak.fullname" $ }}-http
              servicePort: http
  {{- end }}
  {{- end }}
{{- end -}}
