{{- if .Values.keycloak.pki.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-pki
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
type: Opaque
data:
  keystore_pass: {{ .Values.keycloak.pki.keystore.password | b64enc | quote }}
  truststore_pass: {{ .Values.keycloak.pki.truststore.password | b64enc | quote }}
{{- end -}}
